-- +goose Up
-- The one thing tracker cannot work without. Every spatial column, index and query in the
-- phases that follow (roadmap §5.1) is provided by this extension, so it is the first
-- migration and nothing may precede it.
--
-- This is NOT redundant with the postgis/postgis image, which pre-creates the extension in
-- POSTGRES_DB from its own initdb scripts. That image is one way to get a database; a
-- managed Postgres, or a plain postgres:16 with the extension merely *available*, are
-- others — and there, nothing creates it until this runs. Doing it here is what makes the
-- schema self-sufficient, independent of how the database was provisioned. The tests run
-- against a pristine `template0` database precisely so that this line is load-bearing and
-- not quietly doing nothing.
CREATE EXTENSION IF NOT EXISTS postgis;

-- +goose Down
-- Deliberately WITHOUT `CASCADE`.
--
-- goose rolls back in reverse order, so by the time this unwinds, every later migration has
-- already dropped its own tables — and with them every geography column depending on this
-- extension. If one is somehow still there, Postgres REFUSES this statement rather than
-- obeying it, and that refusal is the point: `CASCADE` would silently delete the offending
-- column and the table holding it, which is data loss wearing a clean rollback's clothes.
--
-- Known and accepted: on a database provisioned by the postgis/postgis IMAGE, this refuses
-- even with no tracker tables present — the image also installs postgis_topology and
-- postgis_tiger_geocoder, which depend on postgis, and tracker never asked for either. So a
-- full `down-to-0` there stops here with "other objects depend on it". That is a safe,
-- loud, correct refusal to uninstall an extension somebody else's objects are using, and
-- rolling a production database back to version zero is not an operation tracker supports
-- anyway. Rollbacks go to N-1, not to 0.
DROP EXTENSION IF EXISTS postgis;
