package prosegate

import (
	"strings"
	"testing"
)

// The failure this counter exists to avoid: a comment marker inside a string
// literal, and the closing delimiter of a raw string spanning several lines,
// both read exactly like prose to anything matching on line patterns. The
// umbrella's first attempt scored five files that are mostly code between 64%
// and 85% prose that way, and measuring before trimming is the only reason they
// were not gutted.
const markersInStrings = `package sample

const query = ` + "`" + `
SELECT ST_Covers(area, point) -- not a Go comment
FROM geofences
WHERE id = $1
` + "`" + `

func Marker() string {
	return "// this is not a comment"
}

func Block() string {
	return "/* neither is this */"
}
`

func TestAMarkerInsideAStringIsNotProse(t *testing.T) {
	got, generated, err := CountSource("sample.go", []byte(markersInStrings))
	if err != nil {
		t.Fatalf("parsing: %v", err)
	}
	if generated {
		t.Fatalf("sample.go is not a generated file")
	}
	if got.Prose != 0 {
		t.Errorf("prose = %d, want 0: no line here is a comment", got.Prose)
	}
	if got.Code != 12 {
		t.Errorf("code = %d, want 12: every non-blank line, the raw string's interior and its closing delimiter included", got.Code)
	}
}

const directives = `//go:build linux && amd64
// +build linux,amd64

package sample

//go:generate stringer -type=Kind

//go:embed schema.sql
var schema string

//nolint:errcheck
func Kind() int {
	//line sample.go:99
	return 1
}

//nolint
func Other() int {
	// Code generated by hand. DO NOT EDIT.
	return 2
}
`

func TestADirectiveIsCodeAndNeverProse(t *testing.T) {
	got, generated, err := CountSource("sample.go", []byte(directives))
	if err != nil {
		t.Fatalf("parsing: %v", err)
	}
	if generated {
		t.Fatalf("the generated marker here is not in the leading position, so this file is not generated")
	}
	if got.Prose != 0 {
		t.Errorf("prose = %d, want 0: deleting a directive changes what compiles, what is generated or what a linter does, so no run may demand it", got.Prose)
	}
	if got.Code != 16 {
		t.Errorf("code = %d, want 16", got.Code)
	}
}

func TestEveryDirectiveShapeIsRecognised(t *testing.T) {
	for _, text := range []string{
		"//go:build linux",
		"// +build linux",
		"//go:generate stringer",
		"//go:embed x.sql",
		"//go:noinline",
		"//line sample.go:1",
		"/*line sample.go:1*/",
		"//nolint",
		"//nolint:errcheck",
		"//lint:ignore ST1000 reason",
		"//export Name",
		"// Code generated by protoc. DO NOT EDIT.",
	} {
		if !isDirectiveComment(text) {
			t.Errorf("%q is a directive and must count as code", text)
		}
	}
	for _, text := range []string{
		"// Kind reports what this is.",
		"// The ratio is prose over prose plus code.",
		"/* a block of prose */",
		"// TODO: this is prose, not a directive",
		"// see https://example.invalid/x:y",
	} {
		if isDirectiveComment(text) {
			t.Errorf("%q is prose and must not be excused as a directive", text)
		}
	}
}

const generatedFile = `// Code generated by protoc-gen-go. DO NOT EDIT.

package sample

// This narration is not a human's to trim.
//
// It is regenerated whenever the generator runs, so a ceiling that demanded its
// deletion would be demanding a change that does not survive the next build.
func Generated() int { return 1 }
`

func TestAGeneratedFileLeavesTheMeasurement(t *testing.T) {
	got, generated, err := CountSource("sample.go", []byte(generatedFile))
	if err != nil {
		t.Fatalf("parsing: %v", err)
	}
	if !generated {
		t.Fatalf("the leading marker makes this a generated file")
	}
	if got.Counted() != 0 {
		t.Errorf("counted = %d, want 0: a generated file is out of the measurement entirely", got.Counted())
	}
}

const licenceHeader = `// Copyright 2026 The Tracker Authors.
// All rights reserved.
//
// Licensed under a licence this file does not get to delete.

package sample

// Kind reports what this is.
func Kind() int { return 1 }
`

const noLicenceHeader = `package sample

// Kind reports what this is.
func Kind() int { return 1 }
`

func TestALicenceHeaderIsInNeitherCount(t *testing.T) {
	with, _, err := CountSource("with.go", []byte(licenceHeader))
	if err != nil {
		t.Fatalf("parsing: %v", err)
	}
	without, _, err := CountSource("without.go", []byte(noLicenceHeader))
	if err != nil {
		t.Fatalf("parsing: %v", err)
	}
	if with != without {
		t.Errorf("with a licence header %+v, without one %+v: it is prose by any reading and it is not deletable, so counting it either way distorts the ratio", with, without)
	}
}

const trailingNotes = `package sample

const (
	earthRadiusMetres = 6371008.8 // the IUGG mean radius
	maxLatitude       = 90.0      // degrees
)

func Kind() int { return 1 } // the only kind there is
`

func TestATrailingNoteLeavesItsLineAsCode(t *testing.T) {
	got, _, err := CountSource("sample.go", []byte(trailingNotes))
	if err != nil {
		t.Fatalf("parsing: %v", err)
	}
	if got.Prose != 0 {
		t.Errorf("prose = %d, want 0: a line carrying a token is a line of code whatever is appended to it", got.Prose)
	}
	if got.Code != 6 {
		t.Errorf("code = %d, want 6", got.Code)
	}
}

func TestProseIsCounted(t *testing.T) {
	const narrated = `package sample

// Kind reports what this is.
//
// It reports it by returning it. The returning is done with a return
// statement, which returns.
func Kind() int {
	/* The block form
	   counts too. */
	return 1
}
`
	got, _, err := CountSource("sample.go", []byte(narrated))
	if err != nil {
		t.Fatalf("parsing: %v", err)
	}
	if got.Prose != 6 {
		t.Errorf("prose = %d, want 6", got.Prose)
	}
	if got.Code != 4 {
		t.Errorf("code = %d, want 4", got.Code)
	}
	if !got.Above(50) || !got.MajorityProse() {
		t.Errorf("%+v is more narration than code and must read as such", got)
	}
}

func TestAFileWithNoCommentsIsZeroProse(t *testing.T) {
	got, _, err := CountSource("sample.go", []byte("package sample\n\nfunc Kind() int { return 1 }\n"))
	if err != nil {
		t.Fatalf("parsing: %v", err)
	}
	if got.Prose != 0 || got.Code != 2 {
		t.Errorf("got %+v, want 0 prose and 2 code", got)
	}
}

func TestUnparseableSourceIsAnErrorAndNotAScore(t *testing.T) {
	_, _, err := CountSource("broken.go", []byte("package sample\n\nfunc Broken( {\n"))
	if err == nil {
		t.Fatal("a file that does not parse is neither clean nor skipped")
	}
	if !strings.Contains(err.Error(), "broken.go") {
		t.Errorf("the error must name the file, got %v", err)
	}
}
